// Mocks generated by Mockito 5.4.6 from annotations
// in seznam_ghibli/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:seznam_ghibli/api/films/films_client.dart' as _i2;
import 'package:seznam_ghibli/api/locations/locations_client.dart' as _i4;
import 'package:seznam_ghibli/api/models/films.dart' as _i11;
import 'package:seznam_ghibli/api/models/people.dart' as _i12;
import 'package:seznam_ghibli/api/people/people_client.dart' as _i3;
import 'package:seznam_ghibli/api/rest_client.dart' as _i7;
import 'package:seznam_ghibli/api/species/species_client.dart' as _i5;
import 'package:seznam_ghibli/api/vehicles/vehicles_client.dart' as _i6;
import 'package:seznam_ghibli/models/film_rating.dart' as _i9;
import 'package:seznam_ghibli/storage/favorites_storage.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFilmsClient_0 extends _i1.SmartFake implements _i2.FilmsClient {
  _FakeFilmsClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeopleClient_1 extends _i1.SmartFake implements _i3.PeopleClient {
  _FakePeopleClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationsClient_2 extends _i1.SmartFake
    implements _i4.LocationsClient {
  _FakeLocationsClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpeciesClient_3 extends _i1.SmartFake implements _i5.SpeciesClient {
  _FakeSpeciesClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVehiclesClient_4 extends _i1.SmartFake
    implements _i6.VehiclesClient {
  _FakeVehiclesClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i7.RestClient {
  @override
  _i2.FilmsClient get films =>
      (super.noSuchMethod(
            Invocation.getter(#films),
            returnValue: _FakeFilmsClient_0(this, Invocation.getter(#films)),
            returnValueForMissingStub: _FakeFilmsClient_0(
              this,
              Invocation.getter(#films),
            ),
          )
          as _i2.FilmsClient);

  @override
  _i3.PeopleClient get people =>
      (super.noSuchMethod(
            Invocation.getter(#people),
            returnValue: _FakePeopleClient_1(this, Invocation.getter(#people)),
            returnValueForMissingStub: _FakePeopleClient_1(
              this,
              Invocation.getter(#people),
            ),
          )
          as _i3.PeopleClient);

  @override
  _i4.LocationsClient get locations =>
      (super.noSuchMethod(
            Invocation.getter(#locations),
            returnValue: _FakeLocationsClient_2(
              this,
              Invocation.getter(#locations),
            ),
            returnValueForMissingStub: _FakeLocationsClient_2(
              this,
              Invocation.getter(#locations),
            ),
          )
          as _i4.LocationsClient);

  @override
  _i5.SpeciesClient get species =>
      (super.noSuchMethod(
            Invocation.getter(#species),
            returnValue: _FakeSpeciesClient_3(
              this,
              Invocation.getter(#species),
            ),
            returnValueForMissingStub: _FakeSpeciesClient_3(
              this,
              Invocation.getter(#species),
            ),
          )
          as _i5.SpeciesClient);

  @override
  _i6.VehiclesClient get vehicles =>
      (super.noSuchMethod(
            Invocation.getter(#vehicles),
            returnValue: _FakeVehiclesClient_4(
              this,
              Invocation.getter(#vehicles),
            ),
            returnValueForMissingStub: _FakeVehiclesClient_4(
              this,
              Invocation.getter(#vehicles),
            ),
          )
          as _i6.VehiclesClient);
}

/// A class which mocks [FavoritesStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesStorage extends _i1.Mock implements _i8.FavoritesStorage {
  @override
  Map<String, _i9.FilmRating> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <String, _i9.FilmRating>{},
            returnValueForMissingStub: <String, _i9.FilmRating>{},
          )
          as Map<String, _i9.FilmRating>);

  @override
  _i10.Future<void> save(String? filmId, _i9.FilmRating? rating) =>
      (super.noSuchMethod(
            Invocation.method(#save, [filmId, rating]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> saveAll(Map<String, _i9.FilmRating>? ratings) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [ratings]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> remove(String? filmId) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [filmId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [FilmsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilmsClient extends _i1.Mock implements _i2.FilmsClient {
  @override
  _i10.Future<List<_i11.Films>> getFilms({String? fields, int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getFilms, [], {#fields: fields, #limit: limit}),
            returnValue: _i10.Future<List<_i11.Films>>.value(<_i11.Films>[]),
            returnValueForMissingStub: _i10.Future<List<_i11.Films>>.value(
              <_i11.Films>[],
            ),
          )
          as _i10.Future<List<_i11.Films>>);

  @override
  _i10.Future<List<_i11.Films>> getFilmsId({
    required String? id,
    String? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFilmsId, [], {#id: id, #fields: fields}),
            returnValue: _i10.Future<List<_i11.Films>>.value(<_i11.Films>[]),
            returnValueForMissingStub: _i10.Future<List<_i11.Films>>.value(
              <_i11.Films>[],
            ),
          )
          as _i10.Future<List<_i11.Films>>);
}

/// A class which mocks [PeopleClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeopleClient extends _i1.Mock implements _i3.PeopleClient {
  @override
  _i10.Future<List<_i12.People>> getPeople({String? fields, int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getPeople, [], {#fields: fields, #limit: limit}),
            returnValue: _i10.Future<List<_i12.People>>.value(<_i12.People>[]),
            returnValueForMissingStub: _i10.Future<List<_i12.People>>.value(
              <_i12.People>[],
            ),
          )
          as _i10.Future<List<_i12.People>>);

  @override
  _i10.Future<List<_i12.People>> getPeopleId({
    required String? id,
    String? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPeopleId, [], {#id: id, #fields: fields}),
            returnValue: _i10.Future<List<_i12.People>>.value(<_i12.People>[]),
            returnValueForMissingStub: _i10.Future<List<_i12.People>>.value(
              <_i12.People>[],
            ),
          )
          as _i10.Future<List<_i12.People>>);
}
